# Generated by Django 6.0 on 2026-01-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='home.colors'),
        ),
    ]
