# Generated by Django 6.0 on 2026-01-06 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
    ]
