# Generated by Django 6.0 on 2026-01-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='colors',
        ),
    ]
